name: Aaron Bockover
favicon: null
layout_spectrum: 0.5082650596741587
typography_spectrum: 0.9366004141047597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.03297911514528096
  lightness: 0.7832925904076546
  saturation: 0.5369873675517738
  rhythmicContrast: 0.09660025825724006
purpose: []
